import { Flex, useTheme } from "@chakra-ui/react";

export const Dashboard = () => {
  const theme = useTheme();
  return (
    <>
      <Flex
        minH="100%"
        w="100%"
        align="center"
        justify="center"
        direction="column"
      >
        Coming Soon...
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>hi</Flex>
        <Flex>last</Flex>
      </Flex>
    </>
  );
};
