export const surahs = [
  {
    uuid: 1,
    name: 'سُورَةُ ٱلْفَاتِحَةِ',
    transliteration: 'Al-Faatiha',
    meaning: 'The Opening',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 7,
  },
  {
    uuid: 2,
    name: 'سُورَةُ البَقَرَةِ',
    transliteration: 'Al-Baqara',
    meaning: 'The Cow',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 286,
  },
  {
    uuid: 3,
    name: 'سُورَةُ آلِ عِمۡرَانَ',
    transliteration: 'Aal-i-Imraan',
    meaning: 'The Family of Imraan',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 200,
  },
  {
    uuid: 4,
    name: 'سُورَةُ النِّسَاءِ',
    transliteration: 'An-Nisaa',
    meaning: 'The Women',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 176,
  },
  {
    uuid: 5,
    name: 'سُورَةُ المَائـِدَةِ',
    transliteration: 'Al-Maaida',
    meaning: 'The Table',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 120,
  },
  {
    uuid: 6,
    name: 'سُورَةُ الأَنۡعَامِ',
    transliteration: "Al-An'aam",
    meaning: 'The Cattle',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 165,
  },
  {
    uuid: 7,
    name: 'سُورَةُ الأَعۡرَافِ',
    transliteration: "Al-A'raaf",
    meaning: 'The Heights',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 206,
  },
  {
    uuid: 8,
    name: 'سُورَةُ الأَنفَالِ',
    transliteration: 'Al-Anfaal',
    meaning: 'The Spoils of War',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 75,
  },
  {
    uuid: 9,
    name: 'سُورَةُ التَّوۡبَةِ',
    transliteration: 'At-Tawba',
    meaning: 'The Repentance',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 129,
  },
  {
    uuid: 10,
    name: 'سُورَةُ يُونُسَ',
    transliteration: 'Yunus',
    meaning: 'Jonas',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 109,
  },
  {
    uuid: 11,
    name: 'سُورَةُ هُودٍ',
    transliteration: 'Hud',
    meaning: 'Hud',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 123,
  },
  {
    uuid: 12,
    name: 'سُورَةُ يُوسُفَ',
    transliteration: 'Yusuf',
    meaning: 'Joseph',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 111,
  },
  {
    uuid: 13,
    name: 'سُورَةُ الرَّعۡدِ',
    transliteration: "Ar-Ra'd",
    meaning: 'The Thunder',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 43,
  },
  {
    uuid: 14,
    name: 'سُورَةُ إِبۡرَاهِيمَ',
    transliteration: 'Ibrahim',
    meaning: 'Abraham',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 52,
  },
  {
    uuid: 15,
    name: 'سُورَةُ الحِجۡرِ',
    transliteration: 'Al-Hijr',
    meaning: 'The Rock',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 99,
  },
  {
    uuid: 16,
    name: 'سُورَةُ النَّحۡلِ',
    transliteration: 'An-Nahl',
    meaning: 'The Bee',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 128,
  },
  {
    uuid: 17,
    name: 'سُورَةُ الإِسۡرَاءِ',
    transliteration: 'Al-Israa',
    meaning: 'The Night Journey',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 111,
  },
  {
    uuid: 18,
    name: 'سُورَةُ الكَهۡفِ',
    transliteration: 'Al-Kahf',
    meaning: 'The Cave',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 110,
  },
  {
    uuid: 19,
    name: 'سُورَةُ مَرۡيَمَ',
    transliteration: 'Maryam',
    meaning: 'Mary',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 98,
  },
  {
    uuid: 20,
    name: 'سُورَةُ طه',
    transliteration: 'Taa-Haa',
    meaning: 'Taa-Haa',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 135,
  },
  {
    uuid: 21,
    name: 'سُورَةُ الأَنبِيَاءِ',
    transliteration: 'Al-Anbiyaa',
    meaning: 'The Prophets',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 112,
  },
  {
    uuid: 22,
    name: 'سُورَةُ الحَجِّ',
    transliteration: 'Al-Hajj',
    meaning: 'The Pilgrimage',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 78,
  },
  {
    uuid: 23,
    name: 'سُورَةُ المُؤۡمِنُونَ',
    transliteration: 'Al-Muminoon',
    meaning: 'The Believers',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 118,
  },
  {
    uuid: 24,
    name: 'سُورَةُ النُّورِ',
    transliteration: 'An-Noor',
    meaning: 'The Light',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 64,
  },
  {
    uuid: 25,
    name: 'سُورَةُ الفُرۡقَانِ',
    transliteration: 'Al-Furqaan',
    meaning: 'The Criterion',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 77,
  },
  {
    uuid: 26,
    name: 'سُورَةُ الشُّعَرَاءِ',
    transliteration: "Ash-Shu'araa",
    meaning: 'The Poets',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 227,
  },
  {
    uuid: 27,
    name: 'سُورَةُ النَّمۡلِ',
    transliteration: 'An-Naml',
    meaning: 'The Ant',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 93,
  },
  {
    uuid: 28,
    name: 'سُورَةُ القَصَصِ',
    transliteration: 'Al-Qasas',
    meaning: 'The Stories',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 88,
  },
  {
    uuid: 29,
    name: 'سُورَةُ العَنكَبُوتِ',
    transliteration: 'Al-Ankaboot',
    meaning: 'The Spider',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 69,
  },
  {
    uuid: 30,
    name: 'سُورَةُ الرُّومِ',
    transliteration: 'Ar-Room',
    meaning: 'The Romans',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 60,
  },
  {
    uuid: 31,
    name: 'سُورَةُ لُقۡمَانَ',
    transliteration: 'Luqman',
    meaning: 'Luqman',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 34,
  },
  {
    uuid: 32,
    name: 'سُورَةُ السَّجۡدَةِ',
    transliteration: 'As-Sajda',
    meaning: 'The Prostration',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 30,
  },
  {
    uuid: 33,
    name: 'سُورَةُ الأَحۡزَابِ',
    transliteration: 'Al-Ahzaab',
    meaning: 'The Clans',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 73,
  },
  {
    uuid: 34,
    name: 'سُورَةُ سَبَإٍ',
    transliteration: 'Saba',
    meaning: 'Sheba',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 54,
  },
  {
    uuid: 35,
    name: 'سُورَةُ فَاطِرٍ',
    transliteration: 'Faatir',
    meaning: 'The Originator',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 45,
  },
  {
    uuid: 36,
    name: 'سُورَةُ يسٓ',
    transliteration: 'Yaseen',
    meaning: 'Yaseen',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 83,
  },
  {
    uuid: 37,
    name: 'سُورَةُ الصَّافَّاتِ',
    transliteration: 'As-Saaffaat',
    meaning: 'Those drawn up in Ranks',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 182,
  },
  {
    uuid: 38,
    name: 'سُورَةُ صٓ',
    transliteration: 'Saad',
    meaning: 'The letter Saad',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 88,
  },
  {
    uuid: 39,
    name: 'سُورَةُ الزُّمَرِ',
    transliteration: 'Az-Zumar',
    meaning: 'The Groups',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 75,
  },
  {
    uuid: 40,
    name: 'سُورَةُ غَافِرٍ',
    transliteration: 'Ghafir',
    meaning: 'The Forgiver',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 85,
  },
  {
    uuid: 41,
    name: 'سُورَةُ فُصِّلَتۡ',
    transliteration: 'Fussilat',
    meaning: 'Explained in detail',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 54,
  },
  {
    uuid: 42,
    name: 'سُورَةُ الشُّورَىٰ',
    transliteration: 'Ash-Shura',
    meaning: 'Consultation',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 53,
  },
  {
    uuid: 43,
    name: 'سُورَةُ الزُّخۡرُفِ',
    transliteration: 'Az-Zukhruf',
    meaning: 'Ornaments of gold',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 89,
  },
  {
    uuid: 44,
    name: 'سُورَةُ الدُّخَانِ',
    transliteration: 'Ad-Dukhaan',
    meaning: 'The Smoke',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 59,
  },
  {
    uuid: 45,
    name: 'سُورَةُ الجَاثِيَةِ',
    transliteration: 'Al-Jaathiya',
    meaning: 'Crouching',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 37,
  },
  {
    uuid: 46,
    name: 'سُورَةُ الأَحۡقَافِ',
    transliteration: 'Al-Ahqaf',
    meaning: 'The Dunes',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 35,
  },
  {
    uuid: 47,
    name: 'سُورَةُ مُحَمَّدٍ',
    transliteration: 'Muhammad',
    meaning: 'Muhammad',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 38,
  },
  {
    uuid: 48,
    name: 'سُورَةُ الفَتۡحِ',
    transliteration: 'Al-Fath',
    meaning: 'The Victory',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 29,
  },
  {
    uuid: 49,
    name: 'سُورَةُ الحُجُرَاتِ',
    transliteration: 'Al-Hujuraat',
    meaning: 'The Inner Apartments',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 18,
  },
  {
    uuid: 50,
    name: 'سُورَةُ قٓ',
    transliteration: 'Qaaf',
    meaning: 'The letter Qaaf',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 45,
  },
  {
    uuid: 51,
    name: 'سُورَةُ الذَّارِيَاتِ',
    transliteration: 'Adh-Dhaariyat',
    meaning: 'The Winnowing Winds',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 60,
  },
  {
    uuid: 52,
    name: 'سُورَةُ الطُّورِ',
    transliteration: 'At-Tur',
    meaning: 'The Mount',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 49,
  },
  {
    uuid: 53,
    name: 'سُورَةُ النَّجۡمِ',
    transliteration: 'An-Najm',
    meaning: 'The Star',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 62,
  },
  {
    uuid: 54,
    name: 'سُورَةُ القَمَرِ',
    transliteration: 'Al-Qamar',
    meaning: 'The Moon',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 55,
  },
  {
    uuid: 55,
    name: 'سُورَةُ الرَّحۡمَٰن',
    transliteration: 'Ar-Rahmaan',
    meaning: 'The Beneficent',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 78,
  },
  {
    uuid: 56,
    name: 'سُورَةُ الوَاقِعَةِ',
    transliteration: 'Al-Waaqia',
    meaning: 'The Inevitable',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 96,
  },
  {
    uuid: 57,
    name: 'سُورَةُ الحَدِيدِ',
    transliteration: 'Al-Hadid',
    meaning: 'The Iron',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 29,
  },
  {
    uuid: 58,
    name: 'سُورَةُ المُجَادلَةِ',
    transliteration: 'Al-Mujaadila',
    meaning: 'The Pleading Woman',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 22,
  },
  {
    uuid: 59,
    name: 'سُورَةُ الحَشۡرِ',
    transliteration: 'Al-Hashr',
    meaning: 'The Exile',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 24,
  },
  {
    uuid: 60,
    name: 'سُورَةُ المُمۡتَحنَةِ',
    transliteration: 'Al-Mumtahana',
    meaning: 'She that is to be examined',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 13,
  },
  {
    uuid: 61,
    name: 'سُورَةُ الصَّفِّ',
    transliteration: 'As-Saff',
    meaning: 'The Ranks',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 14,
  },
  {
    uuid: 62,
    name: 'سُورَةُ الجُمُعَةِ',
    transliteration: "Al-Jumu'a",
    meaning: 'Friday',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 11,
  },
  {
    uuid: 63,
    name: 'سُورَةُ المُنَافِقُونَ',
    transliteration: 'Al-Munaafiqoon',
    meaning: 'The Hypocrites',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 11,
  },
  {
    uuid: 64,
    name: 'سُورَةُ التَّغَابُنِ',
    transliteration: 'At-Taghaabun',
    meaning: 'Mutual Disillusion',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 18,
  },
  {
    uuid: 65,
    name: 'سُورَةُ الطَّلَاقِ',
    transliteration: 'At-Talaaq',
    meaning: 'Divorce',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 12,
  },
  {
    uuid: 66,
    name: 'سُورَةُ التَّحۡرِيمِ',
    transliteration: 'At-Tahrim',
    meaning: 'The Prohibition',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 12,
  },
  {
    uuid: 67,
    name: 'سُورَةُ المُلۡكِ',
    transliteration: 'Al-Mulk',
    meaning: 'The Sovereignty',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 30,
  },
  {
    uuid: 68,
    name: 'سُورَةُ القَلَمِ',
    transliteration: 'Al-Qalam',
    meaning: 'The Pen',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 52,
  },
  {
    uuid: 69,
    name: 'سُورَةُ الحَاقَّةِ',
    transliteration: 'Al-Haaqqa',
    meaning: 'The Reality',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 52,
  },
  {
    uuid: 70,
    name: 'سُورَةُ المَعَارِجِ',
    transliteration: "Al-Ma'aarij",
    meaning: 'The Ascending Stairways',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 44,
  },
  {
    uuid: 71,
    name: 'سُورَةُ نُوحٍ',
    transliteration: 'Nooh',
    meaning: 'Noah',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 28,
  },
  {
    uuid: 72,
    name: 'سُورَةُ الجِنِّ',
    transliteration: 'Al-Jinn',
    meaning: 'The Jinn',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 28,
  },
  {
    uuid: 73,
    name: 'سُورَةُ المُزَّمِّلِ',
    transliteration: 'Al-Muzzammil',
    meaning: 'The Enshrouded One',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 20,
  },
  {
    uuid: 74,
    name: 'سُورَةُ المُدَّثِّرِ',
    transliteration: 'Al-Muddaththir',
    meaning: 'The Cloaked One',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 56,
  },
  {
    uuid: 75,
    name: 'سُورَةُ القِيَامَةِ',
    transliteration: 'Al-Qiyaama',
    meaning: 'The Resurrection',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 40,
  },
  {
    uuid: 76,
    name: 'سُورَةُ الإِنسَانِ',
    transliteration: 'Al-Insaan',
    meaning: 'Man',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 31,
  },
  {
    uuid: 77,
    name: 'سُورَةُ المُرۡسَلَاتِ',
    transliteration: 'Al-Mursalaat',
    meaning: 'The Emissaries',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 50,
  },
  {
    uuid: 78,
    name: 'سُورَةُ النَّبَإِ',
    transliteration: 'An-Naba',
    meaning: 'The Announcement',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 40,
  },
  {
    uuid: 79,
    name: 'سُورَةُ النَّازِعَاتِ',
    transliteration: "An-Naazi'aat",
    meaning: 'Those who drag forth',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 46,
  },
  {
    uuid: 80,
    name: 'سُورَةُ عَبَسَ',
    transliteration: 'Abasa',
    meaning: 'He frowned',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 42,
  },
  {
    uuid: 81,
    name: 'سُورَةُ التَّكۡوِيرِ',
    transliteration: 'At-Takwir',
    meaning: 'The Overthrowing',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 29,
  },
  {
    uuid: 82,
    name: 'سُورَةُ الانفِطَارِ',
    transliteration: 'Al-Infitaar',
    meaning: 'The Cleaving',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 19,
  },
  {
    uuid: 83,
    name: 'سُورَةُ المُطَفِّفِينَ',
    transliteration: 'Al-Mutaffifin',
    meaning: 'Defrauding',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 36,
  },
  {
    uuid: 84,
    name: 'سُورَةُ الانشِقَاقِ',
    transliteration: 'Al-Inshiqaaq',
    meaning: 'The Splitting Open',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 25,
  },
  {
    uuid: 85,
    name: 'سُورَةُ البُرُوجِ',
    transliteration: 'Al-Burooj',
    meaning: 'The Constellations',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 22,
  },
  {
    uuid: 86,
    name: 'سُورَةُ الطَّارِقِ',
    transliteration: 'At-Taariq',
    meaning: 'The Morning Star',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 17,
  },
  {
    uuid: 87,
    name: 'سُورَةُ الأَعۡلَىٰ',
    transliteration: "Al-A'laa",
    meaning: 'The Most High',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 19,
  },
  {
    uuid: 88,
    name: 'سُورَةُ الغَاشِيَةِ',
    transliteration: 'Al-Ghaashiya',
    meaning: 'The Overwhelming',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 26,
  },
  {
    uuid: 89,
    name: 'سُورَةُ الفَجۡرِ',
    transliteration: 'Al-Fajr',
    meaning: 'The Dawn',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 30,
  },
  {
    uuid: 90,
    name: 'سُورَةُ البَلَدِ',
    transliteration: 'Al-Balad',
    meaning: 'The City',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 20,
  },
  {
    uuid: 91,
    name: 'سُورَةُ الشَّمۡسِ',
    transliteration: 'Ash-Shams',
    meaning: 'The Sun',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 15,
  },
  {
    uuid: 92,
    name: 'سُورَةُ اللَّيۡلِ',
    transliteration: 'Al-Lail',
    meaning: 'The Night',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 21,
  },
  {
    uuid: 93,
    name: 'سُورَةُ الضُّحَىٰ',
    transliteration: 'Ad-Dhuhaa',
    meaning: 'The Morning Hours',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 11,
  },
  {
    uuid: 94,
    name: 'سُورَةُ الشَّرۡحِ',
    transliteration: 'Ash-Sharh',
    meaning: 'The Consolation',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 8,
  },
  {
    uuid: 95,
    name: 'سُورَةُ التِّينِ',
    transliteration: 'At-Tin',
    meaning: 'The Fig',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 8,
  },
  {
    uuid: 96,
    name: 'سُورَةُ العَلَقِ',
    transliteration: 'Al-Alaq',
    meaning: 'The Clot',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 19,
  },
  {
    uuid: 97,
    name: 'سُورَةُ القَدۡرِ',
    transliteration: 'Al-Qadr',
    meaning: 'The Power, Fate',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 5,
  },
  {
    uuid: 98,
    name: 'سُورَةُ البَيِّنَةِ',
    transliteration: 'Al-Bayyina',
    meaning: 'The Evidence',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 8,
  },
  {
    uuid: 99,
    name: 'سُورَةُ الزَّلۡزَلَةِ',
    transliteration: 'Az-Zalzala',
    meaning: 'The Earthquake',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 8,
  },
  {
    uuid: 100,
    name: 'سُورَةُ العَادِيَاتِ',
    transliteration: 'Al-Aadiyaat',
    meaning: 'The Chargers',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 11,
  },
  {
    uuid: 101,
    name: 'سُورَةُ القَارِعَةِ',
    transliteration: "Al-Qaari'a",
    meaning: 'The Calamity',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 11,
  },
  {
    uuid: 102,
    name: 'سُورَةُ التَّكَاثُرِ',
    transliteration: 'At-Takaathur',
    meaning: 'Competition',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 8,
  },
  {
    uuid: 103,
    name: 'سُورَةُ العَصۡرِ',
    transliteration: 'Al-Asr',
    meaning: 'The Declining Day, Epoch',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 3,
  },
  {
    uuid: 104,
    name: 'سُورَةُ الهُمَزَةِ',
    transliteration: 'Al-Humaza',
    meaning: 'The Traducer',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 9,
  },
  {
    uuid: 105,
    name: 'سُورَةُ الفِيلِ',
    transliteration: 'Al-Fil',
    meaning: 'The Elephant',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 5,
  },
  {
    uuid: 106,
    name: 'سُورَةُ قُرَيۡشٍ',
    transliteration: 'Quraish',
    meaning: 'Quraysh',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 4,
  },
  {
    uuid: 107,
    name: 'سُورَةُ المَاعُونِ',
    transliteration: "Al-Maa'un",
    meaning: 'Almsgiving',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 7,
  },
  {
    uuid: 108,
    name: 'سُورَةُ الكَوۡثَرِ',
    transliteration: 'Al-Kawthar',
    meaning: 'Abundance',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 3,
  },
  {
    uuid: 109,
    name: 'سُورَةُ الكَافِرُونَ',
    transliteration: 'Al-Kaafiroon',
    meaning: 'The Disbelievers',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 6,
  },
  {
    uuid: 110,
    name: 'سُورَةُ النَّصۡرِ',
    transliteration: 'An-Nasr',
    meaning: 'Divine Support',
    revelationPlace: 'RevelationPlace.Medina',
    totalAyat: 3,
  },
  {
    uuid: 111,
    name: 'سُورَةُ المَسَدِ',
    transliteration: 'Al-Masad',
    meaning: 'The Palm Fibre',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 5,
  },
  {
    uuid: 112,
    name: 'سُورَةُ الإِخۡلَاصِ',
    transliteration: 'Al-Ikhlaas',
    meaning: 'Sincerity',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 4,
  },
  {
    uuid: 113,
    name: 'سُورَةُ الفَلَقِ',
    transliteration: 'Al-Falaq',
    meaning: 'The Dawn',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 5,
  },
  {
    uuid: 114,
    name: 'سُورَةُ النَّاسِ',
    transliteration: 'An-Naas',
    meaning: 'Mankind',
    revelationPlace: 'RevelationPlace.Mecca',
    totalAyat: 6,
  },
];
